#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

if [[ -z "$4" ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

# named variables  to be used
path_to_file=$1
ip=$2
username=$3
path_to_private_key=$4

# scp; file transfer protocol
scp -o  StrictHostKeyChecking=no -i "$path_to_private_key" "$path_to_file" "$username@$ip:~/"
