#!/usr/bin/env bash
# install and configure HA proxt on your lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo echo "
frontend my_frontend
	bind *:80
	default_backend my_backend

backend my_backend
	balance roundrobin
	server 317141-web-01 18.206.207.45:80 check
	server 317141-web-02 100.25.109.79:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
