#!/usr/bin/env bash
#displays "To infinity and beyond" indefinitely and its invicible to sigterm

echo "$$" > /var/run/myscript.pid

function handle_sigterm
{
	echo "I hate the kill command"
	rm  /var/run/myscript.pid
	exit
}

function handle_sigint
{
	echo "Y U no love me?!"
}

function handle_sigquit
{
       rm /var/run/myscript.pid
       exit
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

while [[ 1 -eq 1 ]]
do
	echo "To infinity and beyond"
	sleep 2
done
