#!/usr/bin/env bash
#displays "To infinity and beyond" indefinitely and its invicible to sigterm

function handle_sigterm
{
	echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while [[ 1 -eq 1 ]]
do
	echo "To infinity and beyond"
	sleep 2
done
