#!/usr/bin/env bash
# Read the /etc/passwd file line by line using a while loop and IFS=: as the field separator

while IFS=: read -r username x uid gid fullname homedir shell; do
    password=$(grep "^$username:" /etc/shadow | cut -d ":" -f 2)

    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $fullname"
done < /etc/passwd

