#!/usr/bin/env bash
# if condition is added to print Hi when i  is 9

i=1
while [[ $i -le 10 ]] 
do 
	if [[ $i -eq 4 ]]; then
		echo "bad luck"
	elif [[ $i -eq 8 ]]; then
		echo "good luck"
	else
		echo "Best School"

	fi
	i=$((i+1))

done
