#!/usr/bin/env bash
# if condition is added to print  at specific points

i=1
while [[ $i -le 20 ]] 
do
        echo "$i"	
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from italy"
			;;
	esac
	i=$((i+1))

done
