#!/usr/bin/env bash
# changes localhost;127.0.0.1 to 127.0.0.2
# changes facebook.com to 8.8.8.8

cp /etc/passwd ~/temp
cp /etc/hosts ~/temp
sed -i a/127.0.0.1/127.0.0.2/ ~/temp
echo "8.8.8.8 facebook.com" >> ~/temp
cp -f ~/temp /etc/hosts
